# Generated by Django 4.2.15 on 2024-09-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
